backend:
  name: git-gateway
  branch: main # Change this to master if your default GitHub branch is master

media_folder: "src/assets/images" # Where new images will be uploaded
public_folder: "/assets/images"   # The web path to those images

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/content/articles" # Maps to your existing article collection path
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/article.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "videos"
    label: "Videos"
    folder: "src/content/videos" # Maps to your existing video collection path
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/video.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
